include: 'https://gitlab.com/gitlab-cd/ssh-template/raw/master/ssh.yml'

stages:
  - build
  - deploy

.master_environment:
  environment:
    name: master
    url: https://master.krym-project.cloud
  
.develop_environment:
  environment:
    name: develop
    url: https://develop.krym-project.cloud

.build_template:
  image: docker:19.03.1
  stage: build
  services:
    - docker:19.03.1-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo $IMAGE_TAG
    - docker pull $IMAGE_TAG || true
    - echo "Build image for $URL_API"
    - docker build -t $IMAGE_TAG . --build-arg URL_API=$URL_API --compress --cache-from $IMAGE_TAG
    - docker push $IMAGE_TAG 

.deploy_template:
  image: alpine:3.11
  stage: deploy
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-latest
    SSH_PARAMS: $REMOTE_USER $REMOTE_HOST
  script:
    - apk update && apk add openssh
    - echo $SSH_PARAMS
    - ssh_run $SSH_PARAMS "$SSH_PRIVATE_KEY" "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh_run $SSH_PARAMS "$SSH_PRIVATE_KEY" "docker pull $IMAGE_TAG"
    - ssh_run $SSH_PARAMS "$SSH_PRIVATE_KEY" "docker stop krym-$CI_COMMIT_BRANCH || true"    
    - ssh_run $SSH_PARAMS "$SSH_PRIVATE_KEY" "docker rm krym-$CI_COMMIT_BRANCH || true"
    - ssh_run $SSH_PARAMS "$SSH_PRIVATE_KEY" "docker run -d --name krym-$CI_COMMIT_BRANCH --restart=on-failure:10 -p 127.0.0.1:$PORT:3000 $IMAGE_TAG"       
    # - ssh_run $SSH_PARAMS "$SSH_PRIVATE_KEY" "docker image prune -f" || true   
    
    
build develop:
  extends: 
  extends:
    - .build_template
    - .develop_environment
  only:
    - develop

deploy develop:
  extends: 
    - .deploy_template
    - .develop_environment
  variables: 
    PORT: 3000
  only:
    - develop

build master:
  extends: 
  extends:
    - .build_template
    - .master_environment
  only:
    - master

deploy master:
  extends: 
    - .deploy_template
    - .master_environment
  variables: 
    PORT: 3001
  only:
    - master