include: 'https://gitlab.com/gitlab-cd/ssh-template/raw/master/ssh.yml'

stages:
  - build
  - deploy

build stage:
  image: node:10.15.0-stretch
  stage: build
  only:
    - tags
  script:
    - npm ci
    - cp .env.example.js .env.js
    - npm run build
deploy stage:
  stage: deploy
  only:
    - tags
  script:
    - ssh_run "$REMOTE_USER" "$REMOTE_HOST" "$SSH_PRIVATE_KEY" "ls -la"
    - ssh_run "$REMOTE_USER" "$REMOTE_HOST" "$SSH_PRIVATE_KEY" "ls -la"

build master:
  image: node:10.15.0-stretch
  stage: build
  only:
    - master
  script:
    - npm ci
    - cp .env.example.js .env.js
    - npm run build

deploy master:
  stage: deploy
  only:
    - master
  script:
    - ssh_run "$REMOTE_USER" "$REMOTE_HOST" "$SSH_PRIVATE_KEY" "ls -la"
    - ssh_run "$REMOTE_USER" "$REMOTE_HOST" "$SSH_PRIVATE_KEY" "ls -la"